### PR TITLE
Add Comments To Explan Functionality

### LINKED ISSUE #2: [DOCS] Write comments
Try to understand what the code does and write a comment on how it works in HTML, CSS, JS files.

### PR DESCRIPTION
**Pull request by RohitRajvaidya5**
Fixes #2

Added some comments to explain how all songs are played and how dark mode and light mode works.

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
Perfect! But can you do this in CSS as well? If not, will merge..

**Comment by KendallDoesCoding** [comment]
@RohitRajvaidya5 why did you delete the branch and close this PR, you couldv'e just editted css within this branch? Request you to please restore the branch asap.

**Comment by KendallDoesCoding** [comment]
I even said, if you can't do the css, the PR works great and will merge 😆

**Comment by RohitRajvaidya5** [comment]
I am new to github I didn't realise what I did? 😅

**Comment by RohitRajvaidya5** [comment]
I am new to github I didn't realise what I did? 😅

**Comment by KendallDoesCoding** [comment]
> I am new to github I didn't realise what I did? 😅

No worries.

You restored the branch but instead of reopening this PR you made a new pr #5 , I'll close that and reopen this one.

To edit the file to add comments in css, just edit it in the https://github.com/RohitRajvaidya5/let-it-be/tree/NewBranch branch.. If you need any help lemme know.

**Comment by RohitRajvaidya5** [comment]
what should I do now?

**Comment by KendallDoesCoding** [comment]
> To edit the file to add comments in css, just edit it in the https://github.com/RohitRajvaidya5/let-it-be/tree/NewBranch branch.. If you need any help lemme know.

**Review by RohitRajvaidya5 — COMMENTED** [review]
Add Comments in Css

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @RohitRajvaidya5!!

**Comment by RohitRajvaidya5** [comment]
Now I can delete branch right?

**Comment by KendallDoesCoding** [comment]
> Now I can delete branch right?

yes!!

**Pull request merged**
