### PR TITLE
Fixed a minor grammatical error in a comment

### PR DESCRIPTION
**Pull request by mukul314**
Although no one would care about a grammatical mistake in a comment , I thought that we should keep it as neat as possible.

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
Thanks a lot! Is this the only place where the comment is?

Also, this is the project for the album Let It Be but it's not the main project. Will merge this if this is the only comment in which the issue takes place but can you do the same in the main repo ([https://github.com/KendallDoesCoding/mogul-christmas](https://github.com/KendallDoesCoding/mogul-christmas))?

Thanks a ton,
KendallDoesCoding

**Comment by mukul314** [comment]
Yes i guess the other comments were fine, as far as I know only this one
had the error.

**Comment by KendallDoesCoding** [comment]
Thanks! Will merge in a bit

**Comment by KendallDoesCoding** [comment]
Can you help making the change here as well? https://github.com/KendallDoesCoding/mogul-christmas

**Comment by mukul314** [comment]
Yeah sure, I'll try my best !!

**Comment by KendallDoesCoding** [comment]
Thanks!

**Pull request merged**
